#!/usr/bin/env bash
set -euo pipefail
#set -x

# echo -e "/** Embedded GIT describe output for this build\n *\n * Autogenerated file - do not change by hand.\n */"
# echo "module git_describe.d;"
# echo "immutable char[] _gitversion = ["
# printf "%s" $(git describe) | xxd -i -
# echo "];"

printf "%s" $(git describe)
